name: Build docker image
on: [push]
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1.5
      - name: Build image
        run: guix pack -S /bin=bin -f docker --entry-point=bin/fuglesteg.net --root fuglesteg.net-docker.tar.gz -m manifest.scm
      - name: Load image
        run: docker load -i fuglesteg.net-docker.tar.gz
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag image
        run: docker image tag fuglesteg.net fuglesteg/fuglesteg.net:latest
      - name: Push to Docker hub
        run: docker image push -a fuglesteg/fuglesteg.net
